# Generated by Django 5.2.11 on 2026-03-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
